version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
   wordpress:
     depends_on:
       - db
     build: .
     container_name: "elementor_parser"
     ports:
       - "8005:80"
     volumes:
      #- ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./elementor_outside:/var/www/html/wp-content/plugins/elementor_outside
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
      
